all:
  children:
    routers:
      hosts:
        mx960:
          ansible_host: 172.20.20.10
        ne8000:
          ansible_host: 172.20.20.11

    switches:
      hosts:
        sw-access-1:
          ansible_host: 172.20.20.20

  vars:
    ansible_user: admin
    ansible_password: admin123
    ansible_connection: network_cli
    ansible_become: false
